image: hyperized/ansible-docker-image:ubuntu1404-frontend

cache:
  paths:
    - node_modules/

build:
  script:
    - echo Installing dependencies
    - yarn install
    - echo Running build for production
    - npm run build
    - echo Uploading dist
    - node s3Upload.js
