image: hyperized/ansible-docker-image:ubuntu1404-frontend

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build_dist:
  stage: build
  script:
    - echo Installing dependencies
    - yarn install
    - echo Running build for production
    - npm run build
  artifacts:
    name: "${CI_BUILD_ID}_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 1 week
    paths:
    - node_modules/
    - dist/

deploy_dev:
  stage: deploy
  script:
    - gulp --aws_key=$INFOMAKER_AWS_ACCESS_KEY_ID --aws_secret=$INFOMAKER_AWS_SECRET_ACCESS_KEY --aws_bucket=$INFOMAKER_AWS_S3_BUCKET_NAME --aws_region=$AWS_REGION dev-deploy-webwriter-config
    - gulp --aws_key=$DEV_AWS_ACCESS_KEY_ID --aws_secret=$DEV_AWS_SECRET_ACCESS_KEY --aws_bucket=$DEV_AWS_S3_BUCKET_NAME --aws_region=$AWS_REGION deploy
  environment: webwriter-dev-fd
  only:
    - develop

deploy_acc:
  stage: deploy
  script:
    - gulp --aws_key=$INFOMAKER_AWS_ACCESS_KEY_ID --aws_secret=$INFOMAKER_AWS_SECRET_ACCESS_KEY --aws_bucket=$INFOMAKER_AWS_S3_BUCKET_NAME --aws_region=$AWS_REGION acc-deploy-webwriter-config
    - gulp --aws_key=$DEV_AWS_ACCESS_KEY_ID --aws_secret=$DEV_AWS_SECRET_ACCESS_KEY --aws_bucket=$ACC_AWS_S3_BUCKET_NAME --aws_region=$AWS_REGION deploy
  environment: webwriter-acc-fd
  when: manual
  only:
    - develop

deploy_prod:
  stage: deploy
  script:
    - gulp --aws_key=$INFOMAKER_AWS_ACCESS_KEY_ID --aws_secret=$INFOMAKER_AWS_SECRET_ACCESS_KEY --aws_bucket=$INFOMAKER_AWS_S3_BUCKET_NAME --aws_region=$AWS_REGION prod-deploy-webwriter-config
    - gulp --aws_key=$PROD_AWS_ACCESS_KEY_ID --aws_secret=$PROD_AWS_SECRET_ACCESS_KEY --aws_bucket=$PROD_AWS_S3_BUCKET_NAME --aws_region=$AWS_REGION deploy
  environment: webwriter-fd
  when: manual
  only:
    - develop
