image: hyperized/ansible-docker-image:ubuntu1404-frontend

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build_dist:
  stage: build
  script:
    - echo Installing dependencies
    - yarn install
    - echo Running build for production
    - npm run build
  artifacts:
    name: "${CI_BUILD_ID}_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 1 week
    paths:
    - node_modules/
    - dist/

deploy_dev_gulp:
  stage: deploy
  script:
    - gulp --aws_key=$AWS_ACCESS_KEY_ID --aws_secret=$AWS_SECRET_ACCESS_KEY --aws_bucket=$DEV_AWS_S3_BUCKET_NAME --aws_region=$AWS_REGION deploy
  environment: webwriter-dev-fd
  when: manual
  only:
    - gulp-s3-deployment

deploy_acc_gulp:
  stage: deploy
  script:
    - gulp --aws_key=$AWS_ACCESS_KEY_ID --aws_secret=$AWS_SECRET_ACCESS_KEY --aws_bucket=$ACC_AWS_S3_BUCKET_NAME --aws_region=$AWS_REGION deploy
  environment: webwriter-acc-fd
  when: manual
  only:
    - gulp-s3-deployment
