image: mkenney/npm:debian

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update

build:
  script:
    - echo Installing dependencies
    - npm install
    - Running build for production
    - npm run dev
    - Uploading dist
    - AWS_ACCESS_KEY_ID=$AWS_ACCES_KEY_ID  AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY AWS_S3_BUCKET_NAME=$AWS_S3_BUCKET_NAME node s3Upload.js
