image: hyperized/ansible-docker-image:ubuntu1404-frontend

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build_dist:
  stage: build
  tags:
    - FDMG
  script:
    - echo Installing dependencies
    - yarn install
    - echo Running build for production
    - npm run build
    - gulp --fdmg_services_config_url=http://spring-config-acc-fd.fdmg.org:8088/webwriter --ci_commit_sha=${CI_COMMIT_SHA} generate-config-fd
    - gulp --fdmg_services_config_url=http://spring-config-acc-esb.fdmg.org:8088/webwriter --ci_commit_sha=${CI_COMMIT_SHA} generate-config-esb
    - gulp --fdmg_services_config_url=http://spring-config-acc-pensioenpro.fdmg.org:8088/webwriter --ci_commit_sha=${CI_COMMIT_SHA} generate-config-pensioenpro
  artifacts:
    name: "${CI_BUILD_ID}_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    expire_in: 1d
    paths:
    - node_modules/
    - dist/

deploy_dev_fd:
  stage: deploy
  tags:
      - FDMG
  script:
    - gulp --fdmg_services_config_url=http://spring-config-acc-fd.fdmg.org:8088/webwriter dev-fd-deploy-webwriter-config
  environment: webwriter-dev-fd
  only:
    - develop

deploy_dev_esb:
  stage: deploy
  tags:
      - FDMG
  script:
    - gulp --fdmg_services_config_url=http://spring-config-acc-esb.fdmg.org:8088/webwriter dev-esb-deploy-webwriter-config
  environment: webwriter-dev-esb
  only:
    - develop

deploy_dev_pensioenpro:
  stage: deploy
  tags:
      - FDMG
  script:
    - gulp --fdmg_services_config_url=http://spring-config-acc-pensioenpro.fdmg.org:8088/webwriter dev-pensioenpro-deploy-webwriter-config
  environment: webwriter-dev-pensioenpro
  only:
    - develop

deploy_acc_fd:
  stage: deploy
  tags:
      - FDMG
  script:
    - gulp --fdmg_services_config_url=http://spring-config-acc-fd.fdmg.org:8088/webwriter acc-fd-deploy-webwriter-config
  environment: webwriter-acc-fd
  only:
    - acceptance

deploy_acc_esb:
  stage: deploy
  tags:
      - FDMG
  script:
    - gulp --fdmg_services_config_url=http://spring-config-acc-esb.fdmg.org:8088/webwriter acc-esb-deploy-webwriter-config
  environment: webwriter-acc-esb
  only:
    - acceptance

deploy_acc_pensioenpro:
  stage: deploy
  tags:
      - FDMG
  script:
    - gulp --fdmg_services_config_url=http://spring-config-acc-pensioenpro.fdmg.org:8088/webwriter acc-pensioenpro-deploy-webwriter-config
  environment: webwriter-acc-pensioenpro
  only:
    - acceptance

deploy_prod_fd:
  stage: deploy
  tags:
      - FDMG
  script:
    - gulp --fdmg_services_config_url=http://spring-config-acc-fd.fdmg.org:8088/webwriter prod-fd-deploy-webwriter-config
  environment: webwriter-fd
  only:
    - production

deploy_prod_esb:
  stage: deploy
  tags:
      - FDMG
  script:
    - gulp --fdmg_services_config_url=http://spring-config-acc-esb.fdmg.org:8088/webwriter prod-esb-deploy-webwriter-config
  environment: webwriter-esb
  only:
    - production

deploy_prod_pensioenpro:
  stage: deploy
  tags:
      - FDMG
  script:
    - gulp --fdmg_services_config_url=http://spring-config-acc-pensioenpro.fdmg.org:8088/webwriter prod-pensioenpro-deploy-webwriter-config
  environment: webwriter-pensioenpro
  only:
    - production

# Manual deployment of any branch
manual_dev_fd:
  stage: deploy
  tags:
      - FDMG
  script:
    - gulp --fdmg_services_config_url=http://spring-config-acc-fd.fdmg.org:8088/webwriter dev-fd-deploy-webwriter-config
  environment: webwriter-dev-fd
  when: manual

manual_dev_esb:
  stage: deploy
  tags:
      - FDMG
  script:
    - gulp --fdmg_services_config_url=http://spring-config-acc-esb.fdmg.org:8088/webwriter dev-esb-deploy-webwriter-config
  environment: webwriter-dev-esb
  when: manual

manual_dev_pensioenpro:
  stage: deploy
  tags:
      - FDMG
  script:
    - gulp --fdmg_services_config_url=http://spring-config-acc-pensioenpro.fdmg.org:8088/webwriter dev-pensioenpro-deploy-webwriter-config
  environment: webwriter-dev-pensioenpro
  when: manual
